version: '2'
services:
    db:
      image: microsoft/mssql-server-linux
      restart: always
      environment:
        MSSQL_SA_PASSWORD: P2ssw0rd
        ACCEPT_EULA: Y

    web:
      build: ./CloudPlatformsComment
      depends_on:
        - db
      links:
        - db
      ports:
        - "5000:80"
      restart: always
      environment:
        ASPNETCORE_ENVIRONMENT: Production